oauth_token = "jqatteMQcoI3jPrxyXE1A4w_Css6WYY609otw7-IwP0.f_tY-94jZcwPiQVrXx4e1ZG4r5Q056TJvWr-ttfDMYI"
expiration_time = "2025-10-22T12:58:20.883Z"
refresh_token = "ZPt38c4UC9mb7yxAUpV4XWEiBpc2qqe4ze6T3YL_7UQ.rlS9FEqylB7ezFcfBRGgAnHvAkD2oK1t9yYEppgumfE"
scopes = [
  "account:read",
  "user:read",
  "workers:write",
  "workers_kv:write",
  "workers_routes:write",
  "workers_scripts:write",
  "workers_tail:read",
  "d1:write",
  "pages:write",
  "zone:read",
  "ssl_certs:write",
  "ai:write",
  "queues:write",
  "pipelines:write",
  "secrets_store:write",
  "containers:write",
  "cloudchamber:write",
  "offline_access"
]
