oauth_token = "B9yDmZU-6dyotnkwAC_Z_Sb7ylG6_pPL2g-zKl7eh7c.bZPpDGqDIeVScyEtUOI-PCdf3PptJgcGHtg-0tCKW-M"
expiration_time = "2025-12-10T05:03:10.066Z"
refresh_token = "6vzZ-CcRPMsukpFk1N6NiZam7aUihjrnM8-GBPp7e1k.GfRAAis2X3169Utcjk6DrlOrORANhtX7NHS778LgID4"
scopes = [
  "account:read",
  "user:read",
  "workers:write",
  "workers_kv:write",
  "workers_routes:write",
  "workers_scripts:write",
  "workers_tail:read",
  "d1:write",
  "pages:write",
  "zone:read",
  "ssl_certs:write",
  "ai:write",
  "queues:write",
  "pipelines:write",
  "secrets_store:write",
  "containers:write",
  "cloudchamber:write",
  "offline_access"
]
