oauth_token = "waNPD1toOngPRBn_hY5zKRUsQ4UIwz-KTGRC2Ne59KE.R2Hz7E42vNEGn_dNfW03o5QUbHTnTM-eFdEcC4W1ApY"
expiration_time = "2026-02-11T12:21:50.215Z"
refresh_token = "ThpwiTFmIBVD52jftGp4AMc8HaUU3aR0BegzArsj9dc.5N9T7oaAwHpdrY9vfaYzImuoJZtdsxg0HtzQhJCG4qc"
scopes = [
  "account:read",
  "user:read",
  "workers:write",
  "workers_kv:write",
  "workers_routes:write",
  "workers_scripts:write",
  "workers_tail:read",
  "d1:write",
  "pages:write",
  "zone:read",
  "ssl_certs:write",
  "ai:write",
  "queues:write",
  "pipelines:write",
  "secrets_store:write",
  "containers:write",
  "cloudchamber:write",
  "offline_access"
]
