-- Generated from all static t()/$t() calls in pages/**/*.vue.
-- Shared keys remain route = all.

UPDATE page_lang SET route = '[format]-to-webp' WHERE route = 'all' AND key IN (
  'webp.batch_message',
  'webp.clear',
  'webp.desc',
  'webp.download_img',
  'webp.download_zip',
  'webp.error',
  'webp.intro',
  'webp.local_message',
  'webp.no_file',
  'webp.selected',
  'webp.seo_desc',
  'webp.seo_keywords',
  'webp.seo_title',
  'webp.start',
  'webp.success',
  'webp.title',
  'webp.upload'
);

UPDATE page_lang SET route = 'about' WHERE route = 'all' AND key IN (
  'about.blogText',
  'about.blogTitle',
  'about.contactEmail',
  'about.langsList1',
  'about.langsList2',
  'about.langsList3',
  'about.langsTitle',
  'about.meText1',
  'about.meTitle',
  'about.toolsText',
  'about.toolsTitle'
);

UPDATE page_lang SET route = 'auth/login' WHERE route = 'all' AND key IN (
  'auth.login_failed',
  'auth.login_success',
  'auth.no_account',
  'auth.register_now',
  'login.submit',
  'login.title',
  'login.welcome'
);

UPDATE page_lang SET route = 'auth/register' WHERE route = 'all' AND key IN (
  'auth.confirm_password',
  'auth.have_account',
  'auth.login_here',
  'auth.password_mismatch',
  'auth.register',
  'auth.register_btn',
  'auth.register_failed',
  'auth.username'
);

UPDATE page_lang SET route = 'blog' WHERE route = 'all' AND key IN (
  'blog.fetchError',
  'blog.go',
  'blog.gotoPage',
  'blog.items',
  'blog.needLogin',
  'blog.pageSize',
  'blog.posted',
  'blog.seoDesc',
  'blog.seoKeywords',
  'blog.title',
  'blog.totalItems',
  'blog.type',
  'blog.write'
);

UPDATE page_lang SET route = 'blog/[id]' WHERE route = 'all' AND key IN (
  'blog.backToList',
  'blog.category',
  'blog.collapseCatalog',
  'blog.defaultTitle',
  'blog.edit',
  'blog.expandCatalog',
  'blog.lastUpdate',
  'common.loading'
);

UPDATE page_lang SET route = 'date-format' WHERE route = 'all' AND key IN (
  'dateFormat.alt',
  'dateFormat.badge',
  'dateFormat.best',
  'dateFormat.bestFormat',
  'dateFormat.clear',
  'dateFormat.confidence',
  'dateFormat.copyResult',
  'dateFormat.copyScript',
  'dateFormat.copyUtc',
  'dateFormat.decodeResult',
  'dateFormat.description',
  'dateFormat.detectedResult',
  'dateFormat.faqTitle',
  'dateFormat.fillSample',
  'dateFormat.formatAuto',
  'dateFormat.generateLanguage',
  'dateFormat.inputLabel',
  'dateFormat.loadSample',
  'dateFormat.messages.copyFailed',
  'dateFormat.messages.noOutput',
  'dateFormat.messages.noScript',
  'dateFormat.messages.noUtcData',
  'dateFormat.messages.outputCopied',
  'dateFormat.messages.scriptCopied',
  'dateFormat.messages.utcCopied',
  'dateFormat.noInput',
  'dateFormat.outputFormat',
  'dateFormat.parsedCount',
  'dateFormat.placeholder',
  'dateFormat.recognitionTitle',
  'dateFormat.resultPlaceholder',
  'dateFormat.runDemo',
  'dateFormat.runLocal',
  'dateFormat.runOutput',
  'dateFormat.scriptTitle',
  'dateFormat.seoDescription',
  'dateFormat.seoKeywords',
  'dateFormat.seoTitle',
  'dateFormat.support.chineseDate',
  'dateFormat.support.excelDate',
  'dateFormat.support.mixedInput',
  'dateFormat.support.unixMicroseconds',
  'dateFormat.support.unixMilliseconds',
  'dateFormat.support.unixSeconds',
  'dateFormat.supportedFormats',
  'dateFormat.title',
  'dateFormat.whyThis'
);

UPDATE page_lang SET route = 'font-compress' WHERE route = 'all' AND key IN (
  'font.char_count',
  'font.clear',
  'font.compressed_size',
  'font.download',
  'font.error',
  'font.input_chars',
  'font.input_placeholder',
  'font.only_glyphs',
  'font.origin_size',
  'font.output_type',
  'font.selected',
  'font.start',
  'font.success',
  'font.text_selected',
  'font.upload',
  'font.upload_text'
);

UPDATE page_lang SET route = 'id-photo' WHERE route = 'all' AND key IN (
  'idPhoto.adjust',
  'idPhoto.bgColor',
  'idPhoto.brightness',
  'idPhoto.brushCutout',
  'idPhoto.brushSize',
  'idPhoto.brushSizeValue',
  'idPhoto.cleared',
  'idPhoto.contrast',
  'idPhoto.crop',
  'idPhoto.custom',
  'idPhoto.cutout',
  'idPhoto.cutoutError',
  'idPhoto.cutoutSuccess',
  'idPhoto.download',
  'idPhoto.left',
  'idPhoto.paintHint',
  'idPhoto.paintSuccess',
  'idPhoto.preview',
  'idPhoto.processing',
  'idPhoto.reUpload',
  'idPhoto.removePaintedArea',
  'idPhoto.resetCrop',
  'idPhoto.saturation',
  'idPhoto.seoDesc',
  'idPhoto.seoKeywords',
  'idPhoto.size',
  'idPhoto.startPainting',
  'idPhoto.stopPainting',
  'idPhoto.subtitle',
  'idPhoto.title',
  'idPhoto.top',
  'idPhoto.uploadHint',
  'idPhoto.uploadText',
  'idPhoto.zoom'
);

UPDATE page_lang SET route = 'image-compress' WHERE route = 'all' AND key IN (
  'compress.clearAll',
  'compress.downloadAll',
  'compress.format',
  'compress.images',
  'compress.maxDim',
  'compress.originalSize',
  'compress.processing',
  'compress.quality',
  'compress.savingsRate',
  'compress.seoDesc',
  'compress.settings',
  'compress.start',
  'compress.subtitle',
  'compress.title',
  'compress.totalSaved',
  'compress.uploadHint',
  'compress.uploadText'
);

UPDATE page_lang SET route = 'image-generator' WHERE route = 'all' AND key IN (
  'agnesImage.seoDesc',
  'agnesImage.title'
);

UPDATE page_lang SET route = 'index' WHERE route = 'all' AND key IN (
  'home.all',
  'home.categories.ai',
  'home.categories.file',
  'home.categories.image',
  'home.categories.text',
  'home.categories.utility',
  'home.categoryTitles.ai',
  'home.categoryTitles.file',
  'home.categoryTitles.image',
  'home.categoryTitles.text',
  'home.categoryTitles.utility',
  'home.description',
  'home.empty',
  'home.eyebrow',
  'home.searchLabel',
  'home.searchPlaceholder',
  'home.seoDescription',
  'home.seoKeywords',
  'home.seoOgDescription',
  'home.seoTitle',
  'home.tags.ai',
  'home.tags.compression',
  'home.tags.development',
  'home.tags.image',
  'home.tags.text',
  'home.title',
  'home.toolBadge',
  'home.tools.aiImage.description',
  'home.tools.aiImage.name',
  'home.tools.aiVideo.description',
  'home.tools.aiVideo.name',
  'home.tools.blog.description',
  'home.tools.blog.name',
  'home.tools.dateFormat.description',
  'home.tools.dateFormat.name',
  'home.tools.fontCompress.description',
  'home.tools.fontCompress.name',
  'home.tools.hash.description',
  'home.tools.hash.name',
  'home.tools.idPhoto.description',
  'home.tools.idPhoto.name',
  'home.tools.imageCompress.description',
  'home.tools.imageCompress.name',
  'home.tools.imageToWebp.description',
  'home.tools.imageToWebp.name',
  'home.tools.jsonCsv.description',
  'home.tools.jsonCsv.name',
  'home.tools.jsonFormatter.description',
  'home.tools.jsonFormatter.name',
  'home.tools.prompts.description',
  'home.tools.prompts.name',
  'home.tools.shareNote.description',
  'home.tools.shareNote.name',
  'home.tools.token.description',
  'home.tools.token.name',
  'home.tools.uppercase.description',
  'home.tools.uppercase.name',
  'home.tools.webpToJpg.description',
  'home.tools.webpToJpg.name',
  'home.tools.webpToPng.description',
  'home.tools.webpToPng.name',
  'menu.desc'
);

UPDATE page_lang SET route = 'json-csv-convert' WHERE route = 'all' AND key IN (
  'jsoncsv.clear',
  'jsoncsv.copy',
  'jsoncsv.copy_fail',
  'jsoncsv.copy_success',
  'jsoncsv.csv_to_json',
  'jsoncsv.csv_to_json_error',
  'jsoncsv.download',
  'jsoncsv.input_placeholder',
  'jsoncsv.json_to_csv',
  'jsoncsv.json_to_csv_error',
  'jsoncsv.paste',
  'jsoncsv.paste_fail',
  'jsoncsv.paste_not_supported',
  'jsoncsv.paste_success',
  'jsoncsv.result_title',
  'jsoncsv.seo_description',
  'jsoncsv.seo_keywords',
  'jsoncsv.seo_title',
  'jsoncsv.title'
);

UPDATE page_lang SET route = 'uppercase' WHERE route = 'all' AND key IN (
  'menu.uppercase',
  'uppercase.clearBtn',
  'uppercase.copyBtn',
  'uppercase.desc',
  'uppercase.inputLabel',
  'uppercase.instructions.clear',
  'uppercase.instructions.convert',
  'uppercase.instructions.copy',
  'uppercase.instructions.input',
  'uppercase.instructions.title',
  'uppercase.outputLabel',
  'uppercase.outputPlaceholder',
  'uppercase.placeholder',
  'uppercase.status.copyError',
  'uppercase.status.copySuccess',
  'uppercase.status.noText',
  'uppercase.title'
);

UPDATE page_lang SET route = 'video-generator' WHERE route = 'all' AND key IN (
  'agnesVideo.seoDesc',
  'agnesVideo.title'
);

UPDATE page_lang SET route = 'webp-to-[target]' WHERE route = 'all' AND key IN (
  'imageConvert.clear',
  'imageConvert.download',
  'imageConvert.progress',
  'imageConvert.selectedCount',
  'imageConvert.start',
  'imageConvert.success',
  'imageConvert.targetFormat',
  'webpTo.batch_message',
  'webpTo.batch_success',
  'webpTo.description',
  'webpTo.intro',
  'webpTo.keywords',
  'webpTo.local_message',
  'webpTo.seoSuffix',
  'webpTo.title'
);
